name = "chatbot-gemini"
compatibility_date = "2024-04-06"

# Tipo do worker (javascript module)
main = "index.js"

# Variáveis de ambiente (substitua com sua chave real da API Gemini)
[vars]
GEMINI_API_KEY = "AIzaSyDRXd6owlK8Wim7l1Lls-vc-5UbcZIrgmU"
